# Generated by Django 5.2.1 on 2025-05-29 17:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContatoSolicitacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('mensagem', models.TextField()),
                ('data_envio', models.DateTimeField(default=django.utils.timezone.now)),
                ('respondido', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'solicitação de contato',
                'verbose_name_plural': 'solicitações de contato',
                'ordering': ['-data_envio'],
            },
        ),
        migrations.CreateModel(
            name='ServicoReforma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('pintura', 'Pintura'), ('eletrica', 'Elétrica'), ('hidraulica', 'Hidráulica'), ('alvenaria', 'Alvenaria'), ('pisos', 'Pisos e Revestimentos'), ('telhado', 'Telhados'), ('jardim', 'Jardins e Paisagismo'), ('completa', 'Reforma Completa')], max_length=20)),
                ('descricao', models.TextField()),
                ('preco_base', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Serviço de Reforma',
                'verbose_name_plural': 'Serviços de Reforma',
            },
        ),
        migrations.AlterField(
            model_name='produto',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='static/app/img'),
        ),
    ]
