# Generated by Django 5.2.1 on 2025-05-30 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_contatosolicitacao_servicoreforma_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='descricao',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
